Traceback (most recent call last):
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/gslee/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/gslee/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
distances = np.linspace(-25, 25, 500).reshape(-1, 1)

gamma1 = 1
gamma2 = 0.01

rbf1 = rbf_kernel(distances, [[0]], gamma=gamma1)
rbf2 = rbf_kernel(distances, [[0]], gamma=gamma2)

fig, ax = plt.subplots()

ax.set_xlabel("Distance from center")
ax.set_ylabel("Distance similiarity")

ax.plot(distances, rbf1, color="blue", label="gamma = 1")
ax.plot(distances, rbf2, color="red", label="gamma = 0.01", linestyle="--")
# ax.tick_params(axis='y', labelcolor=color)

plt.legend(loc="upper left")
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m distances [38;5;241m=[39m [43mnp[49m[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m25[39m, [38;5;241m25[39m, [38;5;241m500[39m)[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m1[39m)
[1;32m      3[0m gamma1 [38;5;241m=[39m [38;5;241m1[39m
[1;32m      4[0m gamma2 [38;5;241m=[39m [38;5;241m0.01[39m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

